name: Rafik Farhad
description: >
    Department of Computer Science & Engineering <br> 
    Shahjalal University of Science & Technology <br> 
    Sylhet, Bangladesh. <br> 
about: >
    Rafik Farhad <br> 
    rafikfarhad@gmail.com <br> 
    Department of Computer Science & Engineering <br>
    Shahjalal University of Science & Technology <br> 
    Sylhet, Bangladesh. <br> 
url: "" #rafikfarhad.github.io"
baseurl: "/" 
markdown: kramdown
highlighter: rouge

gems: [jekyll-paginate,  jekyll-gist]

paginate: 3
 
logo:             logo.png
disqus_shortname:

owner:
  name:           RafikFarhad
  avatar:         "<blockquote class="imgur-embed-pub" lang="en" data-id="a/PRE2x"><a href="//imgur.com/PRE2x"></a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>"
  email:          "rafikfarhad@gmail.com"
  # Social networking links used in footer. Update and remove as you like.
  twitter: twitter.com/rafikfarhad
  github: github.com/RafikFarhad
  stackexchange:
  # For Google Authorship https://plus.google.com/authorship
  google_plus: https://plus.google.com/115023008660903227281

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:
